### PR TITLE
spruce up design, add templatized build

### PR DESCRIPTION
**Pull request by mwcz**
Two things are in this PR.  The first is that the build has been changed from handwritten static HTML, to a template.  `content.toml` has the content, and it gets injected into `index-template.html` and the result is written to `index.html`.

The second thing is a design revamp.

# Before

arcade redhat com_

# After

localhost_3000_ (2)

### CODE REVIEW

**Comment by cybtachyon** [comment]
This is fantastic to see! Great work.

**Comment by mwcz** [comment]
Thanks @cybtachyon, just a small improvement to the status quo.  Sooner or later we may use a proper CMS, or static site generator (my preference), but this will work for now!

**Comment by larmbuster** [comment]
Looks great!

**Comment by Jared-Sprague** [comment]
Looks great to me! 👍

**Review by Jared-Sprague — APPROVED** [review]
Looks good!

**Comment by Jared-Sprague** [comment]
@mwcz Looks like there is a merge conflict, can you resolve that in your PR so we can merge this?

**Pull request merged**
